// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  gettingStarted: [
    { type: 'autogenerated', dirName: 'getting-started' },
  ],
  userGuide: [
    { type: 'autogenerated', dirName: 'user-guide' },
  ],
  api: [
    { type: 'autogenerated', dirName: 'api' },
  ],
  examples: [
    { type: 'autogenerated', dirName: 'examples' },
  ],
  references: [
    'references',
  ],
};

export default sidebars;
